### ISSUE TITLE
[1.16.5-1.3.1] Crash if player dies while "you can't use this item yet" popup is on screen

### ISSUE THREAD

**Issue by lydianlights** [majikdev/rereskillable#15] opened 2021-06-11 22:57 UTC
I was messing around in creative mode while setting up the configs for rereskillable. I switched to survival to test out if it was working for some items and I got killed by a mob. Right after I died (before I could click respawn) the game crashed with `IllegalArgumentException: Player does not have a Skill Model!`.

I'll update if I can reproduce it or get any more info.

EDIT (UPDATE): Okay so I'm 99.9999% sure this happens when the player dies while the popup is on screen telling you that "you can't use this item yet". I was able to reproduce it a few times. It makes sense if it's trying to look at the player's data that doesn't exist after they die. I'll update the issue title.

Here's the crash report:
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/11/21 3:52 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Player does not have a Skill Model!
	at majik.rereskillable.common.capabilities.SkillModel.lambda$get$1(SkillModel.java:102) ~[?:1.3.1] {re:classloading}
	at majik.rereskillable.common.capabilities.SkillModel$$Lambda$13006/17019343.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:296) ~[?:?] {re:classloading}
	at majik.rereskillable.common.capabilities.SkillModel.get(SkillModel.java:101) ~[?:1.3.1] {re:classloading}
	at majik.rereskillable.client.Overlay.onRenderOverlay(Overlay.java:58) ~[?:1.3.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1038_Overlay_onRenderOverlay_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2531/324516712.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:832) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderExperience(ForgeIngameGui.java:585) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:176) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:472) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.31.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$446/1611618052.call(Unknown Source) [forge-1.16.5-36.1.31.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at majik.rereskillable.common.capabilities.SkillModel.lambda$get$1(SkillModel.java:102) ~[?:1.3.1] {re:classloading}
	at majik.rereskillable.common.capabilities.SkillModel$$Lambda$13006/17019343.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:296) ~[?:?] {re:classloading}
	at majik.rereskillable.common.capabilities.SkillModel.get(SkillModel.java:101) ~[?:1.3.1] {re:classloading}
	at majik.rereskillable.client.Overlay.onRenderOverlay(Overlay.java:58) ~[?:1.3.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1038_Overlay_onRenderOverlay_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2531/324516712.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:832) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderExperience(ForgeIngameGui.java:585) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:176) ~[?:?] {re:classloading}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 841, 575
	Level dimension: minecraft:overworld
	Level spawn location: World: (1503,78,30), Chunk: (at 15,4,14 in 93,1; contains blocks 1488,0,16 to 1503,255,31), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Level time: 203104 game time, 97416 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.31.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$446/1611618052.call(Unknown Source) [forge-1.16.5-36.1.31.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1217035720 bytes (1160 MB) / 3047161856 bytes (2906 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.31.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.31.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.31
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		mowziesmobs-1.5.18.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.18              |DONE      |Manifest: NOSIGNATURE
		GlobalGameRules-1.16.4-5.0.1.3.jar                |Global GameRules              |globalgamerules               |5.0.1.3             |DONE      |Manifest: 15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
		Shrines-1.16.5-1.8.0-Beta1.jar                    |Shrines                       |shrines                       |1.16.5-1.8.0-Beta1  |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.0.104.jar                          |Just Enough Items             |jei                           |7.7.0.104           |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |DONE      |Manifest: NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.4-4.5.0.jar                          |Placebo                       |placebo                       |4.5.0               |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.0.4.jar                 |Comforts                      |comforts                      |1.16.5-4.0.0.4      |DONE      |Manifest: NOSIGNATURE
		citadel-1.6.3.jar                                 |Citadel                       |citadel                       |1.6.3               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.10.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.10.1              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |DONE      |Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-1.16.5-10.1.11.jar                      |Bookshelf                     |bookshelf                     |10.1.11             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		snowundertrees-1.16.5-v1.1.4.jar                  |Snow Under Trees              |snowundertrees                |v1.1.4              |DONE      |Manifest: NOSIGNATURE
		RealisticTorches-1.16.5-3.1.2.jar                 |Realistic Torches             |realistictorches              |1.16.5-3.1.2        |DONE      |Manifest: NOSIGNATURE
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.6-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.6-1.16.4        |DONE      |Manifest: NOSIGNATURE
		SnowRealMagic-1.16.4-2.5.7.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.5.7               |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.16.5-3.5.1.jar                             |Kiwi                          |kiwi                          |3.5.1               |DONE      |Manifest: NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.27.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.27            |DONE      |Manifest: NOSIGNATURE
		rereskillable-1.16.5-1.3.1.jar                    |Rereskillable                 |rereskillable                 |1.3.1               |DONE      |Manifest: NOSIGNATURE
		traverse-1.16.4-0.4.3.8.jar                       |Traverse: Reforged            |traverse                      |1.16.4-0.4.3.8      |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.15.jar                      |Carry On                      |carryon                       |1.15.5.15           |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		CraftTweaker-1.16.5-7.1.0.313.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.313           |DONE      |Manifest: NOSIGNATURE
		firstaid-1.9.6-CUSTOM.jar                         |First Aid                     |firstaid                      |1.9.6               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.31-universal.jar                |Forge                         |forge                         |36.1.31             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waddles-1.16.5-0.8.13.jar                         |Waddles                       |waddles                       |1.16.5-0.8.13       |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |DONE      |Manifest: NOSIGNATURE
		dungeonsarise1.16.5-1.2.68a-HF.jar                |Dungeons Arise                |dungeons_arise                |1.2.68a             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.31-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.16.4-1.2.1.jar                        |CoFH Core                     |cofh_core                     |1.2.1               |DONE      |Manifest: NOSIGNATURE
		ensorcellation-1.16.4-1.2.0.jar                   |Ensorcellation                |ensorcellation                |1.2.0               |DONE      |Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Soaring Structures 2.5.2 - 1.16.5.jar             |Soaring Structures            |soaringstructures             |2.5.2 - 1.16.5      |DONE      |Manifest: NOSIGNATURE
		repurposed_structures-1.16.5-2.7.4-forge.jar      |Repurposed Structures         |repurposed_structures         |1.16.5-2.7.4-forge  |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.8.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.8               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |Manifest: NOSIGNATURE
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |DONE      |Manifest: NOSIGNATURE
		baubles-1.8.7.1-1.16.5.jar                        |Baubles                       |baubles                       |1.8.7               |DONE      |Manifest: NOSIGNATURE
		ChunkAnimator-1.16.5-1.2.4.jar                    |Chunk Animator                |chunkanimator                 |1.16.5-1.2.4        |DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.16.5-1.1.5.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.5               |DONE      |Manifest: NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |Manifest: NOSIGNATURE
		StumbleUponCampsites.jar                          |StumbleUponCamps              |stumbleuponcamps              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |DONE      |Manifest: NOSIGNATURE
		corpsecomplex-forge-1.16.5-4.0.2.3.jar            |Corpse Complex                |corpsecomplex                 |1.16.5-4.0.2.3      |DONE      |Manifest: NOSIGNATURE
		lycanitesmobs-1.16.5-2.3.1.0.jar                  |Lycanites Mobs                |lycanitesmobs                 |1.16.5-2.3.1.0      |DONE      |Manifest: NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.16.4-4.5.1.jar                    |FastWorkbench                 |fastbench                     |4.5.1               |DONE      |Manifest: NOSIGNATURE
		sit-1.16.5-v1.3.1.jar                             |Sit                           |sit                           |v1.3.1              |DONE      |Manifest: NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |DONE      |Manifest: NOSIGNATURE
		ToughAsNails-1.16.5-4.0.1.23-universal.jar        |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.15     |DONE      |Manifest: NOSIGNATURE
		survivaloverhaul-1.16.5-0.4.1b.jar                |Survival Overhaul             |survivaloverhaul              |1.16.5-0.4.1b       |DONE      |Manifest: NOSIGNATURE
		globaldataandresourcepacks-1.16.4-1.7.4.jar       |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.16.4-1.7.3        |DONE      |Manifest: NOSIGNATURE
		Chunk Pregenerator-V1.16-3.0.5.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.0.5         |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.1.jar                  |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.1          |DONE      |Manifest: NOSIGNATURE
		antiquewaystones-1.2.jar                          |Antique Waystones             |antiquewaystones              |1.2                 |DONE      |Manifest: NOSIGNATURE
		campfire_overhaul-1.16.5-1.0.4.1.jar              |Campfire Overhaul             |campfire_overhaul             |1.0.4.1             |DONE      |Manifest: NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |DONE      |Manifest: NOSIGNATURE
		architectury-1.17.20-forge.jar                    |Architectury                  |architectury                  |1.17.20             |DONE      |Manifest: NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |Manifest: NOSIGNATURE
		AgeingSpawners-1.16.5-1.1.0.jar                   |Ageing Spawners               |ageingspawners                |1.1.0               |DONE      |Manifest: NOSIGNATURE
		Craftable_NameTag 1.16.x.jar                      |Craftable Name Tag            |bkcraftablenametag            |[1.16,)             |DONE      |Manifest: NOSIGNATURE
		enhancedcelestials-1.0.4-1.16.4.jar               |Enhanced Celestials           |enhancedcelestials            |1.0.4-1.16.4        |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.19.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.19       |DONE      |Manifest: NOSIGNATURE
		InventoryEssentials_1.16.5-2.3.2.jar              |Inventory Essentials          |inventoryessentials           |2.3.2               |DONE      |Manifest: NOSIGNATURE
		CraftableHorseArmour-1.16.5-1.6.jar               |CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.6                 |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.2.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.2        |DONE      |Manifest: NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta16.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta16|DONE      |Manifest: NOSIGNATURE
		DynamicTreesPlus-1.16.5-0.1.0-Beta9.jar           |Dynamic Trees Plus            |dynamictreesplus              |1.16.5-0.1.0-Beta9  |DONE      |Manifest: NOSIGNATURE
		DynamicTreesTraverse-1.16.5-2.2.0.jar             |Dynamic Trees for Traverse    |dttraverse                    |1.16.5-2.2.0        |DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		xptome-1.16.5-v2.1.2.jar                          |XP Tome                       |xpbook                        |v2.1.2              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 196caf69-c99f-4182-a59e-c95d428e9d7b
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
		snowrealmagic:world
	Launched Version: forge-36.1.31
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.11, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
```

**Comment by majikdev** [comment] 2021-06-12 07:39
I can't reproduce it in a single player world, can you elaborate on when the crash happens and add the configuration file (as a .txt please)?

**Comment by majikdev** [comment] 2021-06-13 15:13
Alright for now I added a check for if the capability exists. This should be fixed, but I never managed to reproduce the issue in the first place, so I don't know. If the issue persists, please make another issue with steps to reproduce it.

**Closed by majikdev** 2021-06-13 15:13 UTC
Labels: bug

**Comment by lydianlights** [comment] 2021-06-14 18:17
> 
> 
> Alright for now I added a check for if the capability exists. This should be fixed, but I never managed to reproduce the issue in the first place, so I don't know. If the issue persists, please make another issue with steps to reproduce it.

Sorry for taking a bit to get back to this. I just downloaded the newest version and it seems to be working fine now. I'll keep an eye out though.
